baseurl = "https://offsecdeer.gitlab.io"
title = "Offsec Deer"
copyright = "Copyright (c) 2019, all rights reserved."
canonifyurls = true
languageCode = "en-US"
paginate = 3
theme = "hugo-dusk"

googleAnalytics = ""
disqusShortname = ""

[author]
  name = "Giulio Pierantoni"

SectionPagesMenu = "main"

# use Chroma for syntax highlight
pygmentsStyle = "native" # other dark style options: vim, fruity, monokai
# enable syntax highlight for code blocks
pygmentsCodeFences = true

[[menu.main]]
  name = "Home"
  identifier = "home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "Posts"
  identifier = "post"
  url = "/post/"
  weight = 20

[[menu.main]]
  name = "Tags"
  identifier = "tag"
  url = "/tags/"
  weight = 30

[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/page/about"
  weight = 40

[[menu.main]]
  name = "Contacts"
  identifier = "contacts"
  url = "/page/contacts"
 weight = 50

[params.meta]
  keywords = "blog, tech, hacking, pentesting, ctf, htb, hackthebox, offsec"
  description = "Thoughts and notes on offensive security from a hacking enthusiast of a deer"

[params.colors]
  # hugo-dusk colors
  background = "#101010" # background color for the site
  main = "#99cc66"
  text = "#dbdbdb"
  code-quote-bg = "#1D1F21" # background color for quotes and code blocks
  copyright = "#404040" # copyright text color

[taxonomies]
  tag = "tags"
  category = "categories"
