baseurl = "https://offsecdeer.gitlab.io/"
title = "Offsec Deer"
copyright = "Copyright (c) 2019, all rights reserved."
canonifyurls = true
languageCode = "en-US"
paginate = 6
theme = "deer"

googleAnalytics = "UA-146649509-1"
DisqusShortname = "offsecdeer"

[author]
  name = "Giulio Pierantoni"

SectionPagesMenu = "main"

[[menu.main]]
  name = "Home"
  identifier = "home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "Posts"
  identifier = "post"
  url = "/post/"
  weight = 20

[[menu.main]]
  name = "Tags"
  identifier = "tag"
  url = "/tags/"
  weight = 30

[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/page/about"
  weight = 40

[[menu.main]]
  name = "Contacts"
  identifier = "contacts"
  url = "/page/contacts"
 weight = 50

[params]
  description = "Experiments on offensive security, ROM hacking, programming and more from my journey as a white hat hacker"
  logoimage = "/images/logo.png"

[params.meta]
  keywords = "blog, tech, hacking, pentesting, ctf, htb, hackthebox, offsec"
  description = "Thoughts and notes on offensive security from a hacking enthusiast of a deer"

[params.sidebar]
    disable = true
    enable = false
    ## Specify the order you want sidebar widgets to appear in.
    ## Omitted widgets are not displayed. You can also specify names
    ## for your own custom sidebar widgets (see below)
    #order = [
        ## Enable a Patreon banner that links to your Patreon page
        ## See also: https://bluestnight.com/docs/midnight/users/sidebar/patreon-banner/
        #"patreon",
        ## Enable a widget with links to multiple methods of support
        ## See also: https://bluestnight.com/docs/midnight/users/sidebar/support/
        #"support",
        ## Enable a search field
        ## See also: https://bluestnight.com/docs/midnight/users/sidebar/search/
        #"search",
        ## Enable a recent articles list. Can be configured to use a custom section
        ## See also: https://bluestnight.com/docs/midnight/users/sidebar/recent-posts/
        #"recent",
        ## Enable a list of page categories
        ## Will cause errors if no categories are defined
        #"categories",
        ## Enable a "cloud" of page tags ordered by most common
        ## Will cause errors if no tags are defined    
        #"taglist"
    #]
    ## Some sidebar widgets require extra configuration, like the Patreon one.
    ## If you use the Patreon widget, replace the quoted "username" with your
    ## Patreon username.
    #[params.sidebar.patreon]
        #username = "username"


[params.colors]
  # hugo-dusk colors
  background = "#101010" # background color for the site
  main = "#99cc66"
  text = "#dbdbdb"
  code-quote-bg = "#1D1F21" # background color for quotes and code blocks
  copyright = "#404040" # copyright text color

[taxonomies]
  tag = "tags"
  category = "categories"

